spring:
  profiles:
    active: prod

---
spring:
  profiles: prod
  
  jpa:
    generate-ddl: true

  datasource:
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5

---

spring:
  profiles: dev

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
    initialSize: 5
    removeAbandoned: true
logging:
  level:
    root: WARN
    weekendgaming: TRACE

server:
  port: 8087
